[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cn3s"
version = "0.1.0"
description = "CN3S rainfall-runoff model (Curve Number with Three-Step Antecedent Precipitation)"
requires-python = ">=3.10"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
dev = [
    "mypy",
    "ruff",
    "pytest",
    "numpy-stubs",
]

[tool.hatch.build.targets.wheel]
packages = ["src/cn3s"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = ["C901", "ANN401", "RET504", "EXE002", "T201", "D203", "D212", "TRY300", "BLE001", "S608", "S101", "PLR0913", "S301"]

[tool.mypy]
files = [
    "src/cn3s"
]
strict = true
local_partial_types = true
strict_equality_for_none = true
warn_unreachable = true
follow_imports = "skip"
ignore_missing_imports = true
